-- Supabase SQL Editor で実行してください。
create extension if not exists pgcrypto;

create table if not exists public.hakoniwa_islands (
  serial bigint generated by default as identity primary key,
  island_name text not null,
  password_hash text not null,
  state jsonb not null,
  last_action_turn integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create or replace view public.hakoniwa_public_islands as
select
  serial,
  island_name,
  coalesce((state->>'population')::integer, 0) as population,
  coalesce((state->>'turn')::integer, 0) as turn,
  state
from public.hakoniwa_islands
where deleted_at is null;

create or replace function public.hakoniwa_register(
  p_island_name text,
  p_password text,
  p_state jsonb
) returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_serial bigint;
  v_state jsonb;
begin
  if length(coalesce(p_password, '')) < 1 then
    raise exception 'password is required';
  end if;
  v_state := jsonb_set(p_state, '{islandName}', to_jsonb(coalesce(nullif(p_island_name, ''), 'MyIsland')), true);
  insert into public.hakoniwa_islands (island_name, password_hash, state, last_action_turn)
  values (coalesce(nullif(p_island_name, ''), 'MyIsland'), crypt(p_password, gen_salt('bf')), v_state, coalesce((v_state->>'turn')::integer, 0))
  returning serial into v_serial;
  return v_serial;
end;
$$;

create or replace function public.hakoniwa_login(
  p_serial bigint,
  p_password text
) returns table(serial bigint, island_name text, population integer, turn integer, state jsonb)
language sql
security definer
set search_path = public, extensions
as $$
  select i.serial,
         i.island_name,
         coalesce((i.state->>'population')::integer, 0) as population,
         coalesce((i.state->>'turn')::integer, 0) as turn,
         i.state
  from public.hakoniwa_islands i
  where i.serial = p_serial
    and i.deleted_at is null
    and i.password_hash = crypt(p_password, i.password_hash);
$$;

create or replace function public.hakoniwa_save(
  p_serial bigint,
  p_password text,
  p_state jsonb,
  p_mark_action boolean default false
) returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_turn integer := coalesce((p_state->>'turn')::integer, 0);
begin
  update public.hakoniwa_islands
  set island_name = coalesce(p_state->>'islandName', island_name),
      state = p_state,
      last_action_turn = case when p_mark_action then v_turn else last_action_turn end,
      updated_at = now()
  where serial = p_serial
    and deleted_at is null
    and password_hash = crypt(p_password, password_hash);
  if not found then
    raise exception 'authentication failed';
  end if;
end;
$$;

create or replace function public.hakoniwa_server_timestamp()
returns bigint
language sql
volatile
security definer
set search_path = public
as $$
  select floor(extract(epoch from clock_timestamp()) * 1000)::bigint;
$$;

alter table public.hakoniwa_islands enable row level security;

drop policy if exists "public tourist read" on public.hakoniwa_islands;
create policy "public tourist read" on public.hakoniwa_islands
  for select using (deleted_at is null);

grant select on public.hakoniwa_public_islands to anon, authenticated;
grant execute on function public.hakoniwa_register(text, text, jsonb) to anon, authenticated;
grant execute on function public.hakoniwa_login(bigint, text) to anon, authenticated;
grant execute on function public.hakoniwa_save(bigint, text, jsonb, boolean) to anon, authenticated;
grant execute on function public.hakoniwa_server_timestamp() to anon, authenticated;
